name: sld_database
on:
   push:
     paths:
       - sld_database/*
   pull_request:
     paths:
       - sld_database/*

jobs:
  Check:
    name: Check sld.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: yaml lint
        run: python3 -c "import yaml; f=open('sld_database/sld.yml', 'r'); yaml.safe_load(f);f.close()"
